[package]
name = "mazer-dbg"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.27"
egui = "0.27"
nix = { version = "0.27", features = ["process", "signal", "socket"] }
serde = { version = "1.0", features = ["derive"] }
ipc-channel = "0.19.0"
