[package]
name = "mazer-dbg"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.27"
egui = "0.27"
# libc = "0.2.172"
once_cell = "1.21.3"
interprocess = "2.2.3"
nix = { version = "0.27", features = ["process", "signal", "socket"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ipc-channel = "0.19.0"
bincode = "2.0.1"

