[package]
name = "mazer-dbg"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.27"
egui = "0.27"
# libc = "0.2.172"
once_cell = "1.21.3"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
nix = { version = "0.27", features = ["process", "signal", "socket"] }
tokio = { version = "1.44", features = ["full"] }

