[build]
linker = "clang"
rustflags = ["-Clink-arg=-fuse-ld=lld", "-Zthreads=22", "-Ctarget-cpu=native"]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=--ld-path=wild"]

