[package]
name = "mazer-data-structures"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A minimal, simple math markup language that compiles to HTML, written in Rust"


[dependencies]
faer = "0.21"

[profile.dev.package.faer]
opt-level = 3
